name: Terraform Governance Pipeline

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  governance-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Checkov
        run: pip install checkov

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run Custom Governance Policies
        run: |
          checkov \
          -d . \
          --external-checks-dir policies \
          --check CUSTOM_AWS_002
