name: Terraform Drift Detection

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:

  drift-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Drift Detection
        run: terraform plan -detailed-exitcode
        continue-on-error: true

      - name: Checkov Governance Scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          external-checks-dir: policies
          soft_fail: true
