name: Terraform Production Environment Platform

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:

  terraform-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Run Checkov Governance Scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          external-checks-dir: policies
          soft_fail: true
